spring.application.name=websemantic
# 1. CAMBIO DE PUERTO (Vital)
# Usamos el 8081 para que pueda correr a la vez que tu taller (8080)
server.port=8081

# 2. NOMBRE DE LA APP

# 3. (OPCIONAL) LOGS
# Para ver las consultas SPARQL en la consola
logging.level.org.apache.jena=INFO